BASE: ['']
ReMOTION_MODE: "train_and_test" # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 50
  LR: 3e-4
  MODEL_FILE_NAME: Arsl_BC_PhysMamba_Normal_TemporalBranch
  NUM_CLASSES: 2
  WARMUP_EPOCHS: 20
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: MAHNOB-HCI
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDHWC                 # in MAHNOB !!
    DATA_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion_Preprocessed"    # Processed dataset save path, need to be updated
    # FILE_LIST_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion_Preprocessed"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    LABEL_SOURCE: 'CSV'
    # Add new split parameters for LOSO and subject-level k-fold cross-validation
    SPLIT_METHOD: ''    # Options: "LOSO" or "KFold"
    NUM_FOLDS: 5            # Used when SPLIT_METHOD is "KFold"
    FOLD_INDEX: 0           # Current fold index (0-based) when using KFold
    LABEL_COLUMN: "BC_Arsl" # <--- Should be changed depending on the purpose
    current_subject: null
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized'] #if use physnet, should be DiffNormalized
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128  #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
VALID:
  BATCH_SIZE: 1
  DATA:
    FS: 30
    DATASET: MAHNOB-HCI
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDHWC                 # in MAHNOB !!
    DATA_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion_Preprocessed"    # Processed dataset save path, need to be updated
    # FILE_LIST_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion_Preprocessed"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 0.9
    LABEL_SOURCE : CSV
    SPLIT_METHOD: ''    # Options: "LOSO" or "KFold"
    NUM_FOLDS: 5            # Used when SPLIT_METHOD is "KFold"
    FOLD_INDEX: 0           # Current fold index (0-based) when using KFold
    LABEL_COLUMN: "BC_Arsl" # <--- Should be changed depending on the purpose
    current_subject: null
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized'] #if use physnet, should be DiffNormalized
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128  #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False                   # to use provided validation dataset to find the best epoch, should be false
  BATCH_SIZE: 1
  DATA:
    FS: 30
    DATASET: MAHNOB-HCI
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDHWC                 # in MAHNOB !!
    DATA_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion_Preprocessed"    # Processed dataset save path, need to be updated
    # FILE_LIST_PATH: "/home/changmin/data/MAHNOB_HCI_Emotion_Preprocessed"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.9
    END: 1.0
    LABEL_SOURCE : CSV
    SPLIT_METHOD: ''    # Options: "LOSO" or "KFold"
    NUM_FOLDS: 5            # Used when SPLIT_METHOD is "KFold"
    FOLD_INDEX: 0           # Current fold index (0-based) when using KFold
    LABEL_COLUMN: "BC_Arsl" # <--- Should be changed depending on the purpose
    current_subject: null
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized'] #if use physnet, should be DiffNormalized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128  #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: /home/changmin/log
  # SAVE_PLOTS: True
ENCODER:
  NAME: TemporalBranch
INFERENCE:
  BATCH_SIZE: 1
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""
  # MODEL_PATH: "./pths/BC_Arsl_LOSO_PHYSMAMBA.pth"